# Dockerfile for React Frontend
# Base image for building the React app
FROM node:18-alpine as build
WORKDIR /app

# Copy package files and install dependencies
COPY package*.json ./
RUN npm install

# Copy source code and build the app
COPY . .
RUN npm run build 


FROM nginx:alpine

COPY --from=build /app/dist /usr/share/nginx/html


EXPOSE 80 
CMD ["nginx", "-g", "daemon off;"]